### PR TITLE
move common set up into single setup shell script and git pull command

### LINKED ISSUE #43: [Enhancement suggestion]: add automatic git pull command
### Contact Details

e.j.hannon@exeter.ac.uk

### Enhancement suggestion

To ensure cohorts are using the latest version of the script add a git pull command at the top of each script.

### PR DESCRIPTION
**Pull request by ejh243**
All the scripts have the same first 26 lines or so, to reduce redundancy I have moved this common blurb into a [setup.sh](https://github.com/genetics-of-dna-methylation-consortium/godmc_phase2/blob/43-enhancement-suggestion-add-automatic-git-pull-command/resources/setup.sh) script located in the resources folder. Now if want to make change stop this section we only need to edit it in one place. 

I have also added a git pull command to this script. 

This closes #43 

Would be helpful if someone could test on some actual data before accepting into the pipeline.

### CODE REVIEW

**Comment by SiyiSEA** [comment]
I tested, but it seems that the Parse options is not working in the setup.sh.

Here is my output:

```
[sww208@mrc-comp028 godmc_phase2] $ ./01-check_data.sh -c "/lustre/home/sww208/GoDMC/DataSetGoDMC/scz_ab_eur/scz_ab_eurconfig"
Already up to date.
-----------------------------------------------

Using config located at: ./config

-----------------------------------------------
./01-check_data.sh: line 7: print_version: command not found
grep: /resources/parameters: No such file or directory
There is no method for -c.
Please run:
./01-check_data [arg]
where arg is an optional argument that can be one of:
all
config
download
requirements
genetic
methylation
covariates
covariates_for_PRS
phenotypes_for_PRS
summary


```

**Comment by ejh243** [comment]
Yes I wasn't passing the arguments from the script to the setup.sh script. This should be fixed now.

**Comment by SiyiSEA** [comment]
@epzjlm , Would you mind to reviewing our modifications and test them before merging ?

**Comment by drsora** [comment]
I'm also having this issue. I just ran git pull and when I try to run script 1, I get the following:

`./01-check_data.sh 
Already up to date.
-----------------------------------------------

Using config located at: ./config

-----------------------------------------------
./01-check_data.sh: line 7: print_version: command not found
grep: /resources/parameters: No such file or directory
-----------------------------------------------

config section

to run this part on its own type:
$ ./01-check_data.sh config

-----------------------------------------------


The study name '' is invalid. Please use only alphanumeric or underscore characters, with no spaces or special characters etc.
`

**Comment by SiyiSEA** [comment]
Could @drsora you do `head 01-check_data.sh` for me?

**Comment by drsora** [comment]
> Could @drsora you do `head 01-check_data.sh` for me?

#!/bin/bash

./resources/setup.sh

exec &> >(tee ${section_01_logfile})
exec &> >(tee ${section_01_logfiles})
print_version


containsElement () {
        local e
        for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
        echo "There is no method for ${1}."
        echo "Please run:"
        echo "./01-check_data [arg]"

**Comment by SiyiSEA** [comment]
> > Could @drsora you do `head 01-check_data.sh` for me?
> 
> #!/bin/bash
> 
> ./resources/setup.sh
> 
> exec &> >(tee ${section_01_logfile}) exec &> >(tee ${section_01_logfiles}) print_version
> 
> containsElement () { local e for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done echo "There is no method for ${1}." echo "Please run:" echo "./01-check_data [arg]"

Could you do the git pull mannually? The script lacks of one line of code.

Here how my 01-check_data.sh looks like:

```
#!/bin/bash

source resources/setup.sh "$@"
set -- $concatenated
echo $1
exec &> >(tee ${section_01_logfile})
exec &> >(tee ${section_01_logfiles})
print_version


```

**Comment by drsora** [comment]
> Could you do the git pull mannually? The script lacks of one line of code.

I did, it says that the script is already up to date. 🤔

**Review by drsora — APPROVED** [review]

**Pull request merged**
