### PR TITLE
03g issue with cg07959070

### LINKED ISSUE #13: [Bug]: 03g issue with cg07959070
### Contact Details

sonja.rajic@tuni.fi

### Scripts

03g-perform_positive_control.sh

### What happened?

03g doesn't run fully, output is below
I can't upload 03g because some files are missing, I uploaded a-d

### How can the bug be reproduced?

_No response_

### R version

4.4.0 (April, 2024)

### Python version

None

### Relevant log output

```shell
make manhattan and qq plots
Reading in /data/sonja/godmc/results/03/positive_control_untransformed_cg07959070.PHENO1.glm.linear.gz GWAS results


Expecting a large meQTL near 22:50053871
Lowest p-value within 1e+05 base pairs: 0.00127855
WARNING!
There doesn't appear to be a QTL for this positive control
Please upload this section and contact GoDMC analysts before continuing.


Generating QQ-plot without cis chromosome for/data/sonja/godmc/results/03/positive_control_untransformed_cg07959070 with lambda 0.943745114347533
Generating manhantten plot without cis chromosome /data/sonja/godmc/results/03/positive_control_untransformed_cg07959070
Error in manhattan(man_data, bp = names(man_data)[pos_column], chr = names(man_data)[chr_column],  : 
  #CHROM column should be numeric. Do you have 'X', 'Y', 'MT', etc? If so change to numbers and try again.
Calls: main -> manhattan
Execution halted
```

### PR DESCRIPTION
**Pull request by SiyiSEA**
This pull request addresses issue #13.

The script now checks if the chromosome (chr) column contains X, Y, MT, or PAR values and converts them as follows:

X is converted to 23
Y is converted to 24
MT is converted to 25
PAR are removed.

Additionally, to generate the Manhattan plot, the script ensures that the chromosome, p-value, and position columns are numeric, while the SNP column remains as a character type.

Please test the script before approving. Thanks! 😉

### CODE REVIEW

**Comment by drsora** [comment]
Ran it but I'm getting this error, not sure if it's related to the new code. 

`Reading in /data/sonja/godmc/results/03/positive_control_untransformed_cg07959070.PHENO1.glm.linear.gz GWAS results
[2024-10-17 15:19:51.870508] Exception: No write permission for directory: /tmp/RtmpGS8UZL

  at #09. getWritablePathname.Arguments(static, ...)
          - getWritablePathname.Arguments() is in environment 'R.utils'

  at #08. getWritablePathname(static, ...)
          - getWritablePathname() is in environment 'R.utils'

  at #07. Arguments$getWritablePathname(pathname, mustNotExist = TRUE)
          - Arguments$getWritablePathname() is local of the calling function

  at #06. popTemporaryFile.default(destnameT)
          - popTemporaryFile.default() is in environment 'R.utils'

  at #05. popTemporaryFile(destnameT)
          - popTemporaryFile() is in environment 'R.utils'

  at #04. decompressFile.default(file, decompFile <- tempfile(tmpdir = tmpdir), 
              ext = NULL, FUN = FUN, remove = FALSE)
          - decompressFile.default() is in environment 'R.utils'

  at #03. R.utils::decompressFile(file, decompFile <- tempfile(tmpdir = tmpdir), 
              ext = NULL, FUN = FUN, remove = FALSE)
          - R.utils::decompressFile() is in environment 'R.utils'

  at #02. fread(filename, header = T, data.table = F)
          - fread() is in environment 'data.table'

  at #01. main()
          - main() is in environment 'R_GlobalEnv'

Error: No write permission for directory: /tmp/RtmpGS8UZL`

**Comment by SiyiSEA** [comment]
> /tmp/RtmpGS8UZL

Have you recognise this folder `/tmp/RtmpGS8UZL`?

**Comment by drsora** [comment]
> > /tmp/RtmpGS8UZL
> 
> Have you recognise this folder `/tmp/RtmpGS8UZL`?
> 
> It looks like this issue related with permission on your R/Linux environment.

That's odd, I've never had this kind of an issue and I also can't find the folder. I checked /tmp in general and it seems that I should have write permissions for it. I wonder why it even needs to write anything there though.

**Comment by drsora** [comment]
> Have you ever try to run other R scripts under the same environment? Are they working?

Weirdly enough, I ran 03f and it ran just fine 😅 I have no idea what's going on here. I'll try the mysterious, ancient trick of rebooting everything. I'll let you know if it's magically fixed.

**Comment by drsora** [comment]
apparently the issue is the fread function, it creates a temporary folder and my server seems to have an issue with that. I'm not the admin though so I have to see what I can do about it. I can try to read the data with a different function meanwhile, perhaps

**Review by ejh243 — APPROVED** [review]

**Comment by ejh243** [comment]
@drsora before we merge this change can you pull this branch and test Siyi's fix for 03g? Thanks

**Comment by ejh243** [comment]
@drsora it would also be helpful if you could rerun 02a and 02b to check that our fixes further up the pipeline do what they need to do.

**Review by epzjlm — APPROVED** [review]

**Comment by drsora** [comment]
> @drsora before we merge this change can you pull this branch and test Siyi's fix for 03g? Thanks

I tested it and fixed the issues with my server, works perfectly now!

**Pull request merged**
